### ISSUE TITLE
Multi-part polygons getting coloured differently

### ISSUE THREAD

**Issue by robroc** [geopandas/geopandas#1141]
I have a geodataframe with some multi-part polygons and a RGBA colour column for each one. When I run `.plot()`, multi-part polygons are getting coloured differently for each part, instead of the colour in the colour column.

This is the single row in the geodataframe of the feature:
![data](https://user-images.githubusercontent.com/1219001/65908343-42639c00-e394-11e9-88b3-6b1418407880.PNG)

This is what it looks like highlighted in ArcGIS Pro:
![fsa1](https://user-images.githubusercontent.com/1219001/65908376-514a4e80-e394-11e9-99fd-f3b00337e043.PNG)

And this is how it's coming out with `.plot()`:

![polygons](https://user-images.githubusercontent.com/1219001/65908402-5dcea700-e394-11e9-866b-f93cad5aff96.PNG)

This is happening with all other multi-part features.

Code used:

`gdf.plot(figsize = (25,25), facecolor = year_map.color)`

**Comment by martinfleis** [comment]
Which version of Geopandas do you use? This has been recently fixed in 0.6.

**Comment by robroc** [comment]
I'm was using 0.5.1. Just upgraded to 0.6. Problem is still there.

**Comment by martinfleis** [comment]
That is strange as #1119 should fix this. Can you provide reproducible example?

**Comment by robroc** [comment]
I'll try. The shapefile I used [was this one](https://www12.statcan.gc.ca/census-recensement/alternative_alternatif.cfm?l=eng&dispext=zip&teng=lfsa000b16a_e.zip&k=%20%20%20%2044221&loc=http://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/files-fichiers/2016/lfsa000b16a_e.zip).

The data [is here](https://gist.github.com/robroc/4ce136e171f71833f14c7fe0c67335d1).

```
from matplotlib.colors import to_rgba
import pandas as pd

fsa_shp = geopandas.read_file('gfsa000b11a_e.shp').to_crs(epsg=3347)
elxn_fsa_winners = pd.read_csv('fsa_fundraiser_parties_years.csv')

top_parties = ['Conservative Party of Canada', 'Liberal Party of Canada', 'New Democratic Party', 'Green Party of Canada', 'Bloc Québécois']
party_colors = dict(zip(top_parties, ['blue', 'red', 'orange', 'green', 'deepskyblue']))
colors_dict = {party : (to_rgba(party_colors[party]) if party in party_colors.keys() else to_rgba('grey')) for party in elxn_fsa_winners.winning_party.unique()}

elxn_fsa_winners['color'] = elxn_fsa_winners.winning_party.map(colors_dict)
                  
for year in elxn_fsa_winners.fiscal_election_date.unique():
    year_data = elxn_fsa_winners.query('fiscal_election_date == @year')
    year_map = fsa_shp.merge(year_data, left_on = 'CFSAUID', right_on = 'FSA', how = 'left')
    year_map.color = year_map.color.apply(lambda x: to_rgba('grey') if x is np.nan else x)
    year_map.plot(figsize = (25,25), facecolor = year_map.color)
```

**Comment by martinfleis** [comment]
@robroc are you sure you are using Geopandas 0.6? Below are plot I got based on your code and linked data. There does not seem to be the issue showed above. Have you restarted your kernel after updating? I am unable to reproduce this behaviour. Or is there anything I missed in these plots?

![Unknown](https://user-images.githubusercontent.com/36797143/65913535-05b19800-e3c8-11e9-9f64-4977e92f1fce.png)

![Unknown-1](https://user-images.githubusercontent.com/36797143/65913546-09451f00-e3c8-11e9-8a5a-60e705d6128b.png)
![Unknown-2](https://user-images.githubusercontent.com/36797143/65913551-0b0ee280-e3c8-11e9-881b-4a5087916a5f.png)

**Comment by robroc** [comment]
Oh dear. It was as simple as restarting the kernel. I thought re-importing the package would have been enough. Apologies for the noob mistake and thank you for the fast response.

**Comment by martinfleis** [comment]
@robroc happy it is resolved now. Closing.
