### ISSUE TITLE
QST: KeyError: 'MISSING'?

### ISSUE THREAD

**Issue by abdoulsn** [geopandas/geopandas#1867]
Hello, I installed and used geopandas many time in my laptop, I've an error now `KeyError: 'MISSING'` when I tried to import it. This happened when I removed one of my virtualenv which was not the handler of gpp.
All dependencies are installed and I re-installed geopandas also but this doesn't  fixe my error. What this error mean?

```
import pandas as pd
import geopandas as gpd
import libpysal as lp
import matplotlib.pyplot as plt
import rasterio as rio
import numpy as np
import contextily as ctx
import shapely.geometry as geom


---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-1aa75faa3f6b> in <module>
----> 1 import geopandas as gpd
      2 import pandas as pd
      3 import matplotlib.pyplot as plt
      4 from shapely.geometry import Point

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/geopandas/__init__.py in <module>
      1 from geopandas._config import options  # noqa
      2 
----> 3 from geopandas.geoseries import GeoSeries  # noqa
      4 from geopandas.geodataframe import GeoDataFrame  # noqa
      5 from geopandas.array import points_from_xy  # noqa

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/geopandas/geoseries.py in <module>
     10 from shapely.geometry.base import BaseGeometry
     11 
---> 12 from geopandas.base import GeoPandasBase, _delegate_property
     13 from geopandas.plotting import plot_series
     14 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/geopandas/base.py in <module>
     11 import geopandas as gpd
     12 
---> 13 from .array import GeometryArray, GeometryDtype
     14 from .sindex import get_sindex_class, has_sindex
     15 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/geopandas/array.py in <module>
     23 
     24 from . import _compat as compat
---> 25 from . import _vectorized as vectorized
     26 
     27 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/geopandas/_vectorized.py in <module>
     37 
     38 if compat.USE_PYGEOS:
---> 39     type_mapping = {p.value: _names[p.name] for p in pygeos.GeometryType}
     40     geometry_type_ids = list(type_mapping.keys())
     41     geometry_type_values = np.array(list(type_mapping.values()), dtype=object)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/geopandas/_vectorized.py in <dictcomp>(.0)
     37 
     38 if compat.USE_PYGEOS:
---> 39     type_mapping = {p.value: _names[p.name] for p in pygeos.GeometryType}
     40     geometry_type_ids = list(type_mapping.keys())
     41     geometry_type_values = np.array(list(type_mapping.values()), dtype=object)

KeyError: 'MISSING'
```

**Comment by martinfleis** [comment]
Hi, this is caused by incompatibility between geopandas <0.8.2 and pygeos 0.9. If you can update to 0.8.2 or ideally 0.9.0 version of GeoPandas, the issue should be resolved.

**Comment by abdoulsn** [comment]
Thanks this solved it.

**Comment by procyonlun** [comment]
hello，I updated geopandas and pygeos, but the issue is still not resolved . can u
help me ~

**Comment by martinfleis** [comment]
@procyonlun if you see this issue, then you are using very old version of GeoPandas. You will not see it in any release since 0.8.2. Note that the latest version is 0.11.

**Comment by procyonlun** [comment]
> @procyonlun if you see this issue, then you are using very old version of GeoPandas. You will not see it in any release since 0.8.2. Note that the latest version is 0.11.

thx, but now my current version of Geopandas is 0.11.1 (crying..)

**Comment by procyonlun** [comment]
![bug](https://user-images.githubusercontent.com/114399524/196582963-0b9037fb-c1bb-4b42-813c-4a511acb4c1d.jpg)
this is my pip list

**Comment by procyonlun** [comment]
> geopanda



> @procyonlun it is unlikely then that you are running geopandas in the environment you have shown the pip list for. It would help if from the script you are seeing the error from, add the following lines and show the results:
> 
> ```python
> import geopandas
> print(geopandas.show_versions())
> ```

thx ,I reinstalled geopandas and the problem was solved. Really thx
