### ISSUE TITLE
BUG: Spatial index error using to_postgis with GeoAlchemy2 0.11

### ISSUE THREAD

**Issue by justinanderson** [geopandas/geopandas#2375]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas
from sqlalchemy import create_engine

db_connection_url = "postgresql://postgres:postgres@localhost:5432/foo"
engine = create_engine(db_connection_url) 
gdf = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
gdf.to_postgis('naturalearth_lowres', engine, if_exists='replace')
```

#### Traceback

<details>

Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File ".../lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateTable: relation "idx_naturalearth_lowres_geometry" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.10/site-packages/geopandas/geodataframe.py", line 1808, in to_postgis
    geopandas.io.sql._write_postgis(
  File ".../lib/python3.10/site-packages/geopandas/io/sql.py", line 431, in _write_postgis
    gdf.to_sql(
  File ".../lib/python3.10/site-packages/pandas/core/generic.py", line 2963, in to_sql
    return sql.to_sql(
  File ".../lib/python3.10/site-packages/pandas/io/sql.py", line 697, in to_sql
    return pandas_sql.to_sql(
  File ".../lib/python3.10/site-packages/pandas/io/sql.py", line 1729, in to_sql
    table = self.prep_table(
  File ".../lib/python3.10/site-packages/pandas/io/sql.py", line 1628, in prep_table
    table.create()
  File ".../lib/python3.10/site-packages/pandas/io/sql.py", line 842, in create
    self._execute_create()
  File ".../lib/python3.10/site-packages/pandas/io/sql.py", line 828, in _execute_create
    self.table.create(bind=self.pd_sql.connectable)
  File ".../lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 950, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File ".../lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2119, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File ".../lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File ".../lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 905, in visit_table
    self.traverse_single(index, create_ok=True)
  File ".../lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File ".../lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 936, in visit_index
    self.connection.execute(CreateIndex(index))
  File ".../lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1295, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File ".../lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File ".../lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1387, in _execute_ddl
    ret = self._execute_context(
  File ".../lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1851, in _execute_context
    self._handle_dbapi_exception(
  File ".../lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2032, in _handle_dbapi_exception
    util.raise_(
  File ".../lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File ".../lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File ".../lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "idx_naturalearth_lowres_geometry" already exists

[SQL: CREATE INDEX idx_naturalearth_lowres_geometry ON public.naturalearth_lowres USING gist (geometry)]
(Background on this error at: https://sqlalche.me/e/14/f405)

</details>

#### Problem description

The above code works with GeoAlchemy2 0.10.2, but it seems `to_postgis` always fails with a duplicate spatial index error with GeoAlchemy2 0.11.

This may be related to https://github.com/geoalchemy/geoalchemy2/pull/344, added in 0.11.0, which changed how GeoAlchemy2 creates spatial indexes. I don't know if this exception I'm seeing is a bug in GeoAlchemy2 or a breaking change which GeoPandas needs to account for.

#### Expected Output

The `to_postgis` method should successfully create a table on the PostGIS server without throwing any exceptions.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]
executable : .../bin/python
machine    : macOS-12.2-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.10.2
GEOS lib   : /usr/local/Cellar/geos/3.10.2/lib/libgeos_c.dylib
GDAL       : 3.4.1
GDAL data dir: .../lib/python3.10/site-packages/fiona/gdal_data
PROJ       : 8.2.0
PROJ data dir: .../lib/python3.10/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.4.1
fiona      : 1.8.21
numpy      : 1.22.3
shapely    : 1.8.1.post1
rtree      : None
pyproj     : 3.3.0
matplotlib : 3.5.1
mapclassify: None
geopy      : None
psycopg2   : 2.9.3 (dt dec pq3 ext lo64)
geoalchemy2: 0.10.2
pyarrow    : None
pygeos     : None
</details>

**Comment by thijscobben** [comment]
When I run my code locally, to_postgis works like a charm (to the same server).
When I run remote (k8s pod/Docker container) I get this error too.

geoalchemy in requirements:
geoalchemy2

I will pinpoint a newer version now and see if it resolves.
local version: 0.9.4
I just updated local to 0.11.1 and now it also crashes on to_postgis . 
When I downgrade to 0.10.2 it works again locally.

**Comment by martinfleis** [comment]
Thanks for the report (same to @iboates reporting it in parallel). I believe this is caused by some changes in geoalchemy that may have been unintentional. I opened an issue on their side https://github.com/geoalchemy/geoalchemy2/issues/376

**Comment by martinfleis** [comment]
This is a confirmed issue on geoalchemy2 side. For the time being, I recommend pinning your environments to <0.11.

**Comment by martinfleis** [comment]
This should now be fixed on the master version of geoalchemy2 - https://github.com/geoalchemy/geoalchemy2/pull/374

**Comment by martinfleis** [comment]
Thank you @adrien-berchet !

Can someone with a running PostGIS instance confirm that the issue is fixed?

**Comment by Franc-Brs** [comment]
Hi @martinfleis I found this issue, I have still the same problem with `GeoAlchemy2==0.12.1` but I'm able to build my environment correctly with  `GeoAlchemy2==0.10.2`

**Comment by adrien-berchet** [comment]
Hello @Franc-Brs 
I think your issue is different, could you provide a more complete example please? And maybe you could create a specific issue on the [GeoAlchemy2 tracker](https://github.com/geoalchemy/geoalchemy2/issues).

**Comment by Franc-Brs** [comment]
hi @adrien-berchet and thank you for your answer!

I post here the traceback that I have with GeoAlchemy2==0.12.1 (with 0.10.2 it is ok). If it's not an error of mine I'd like to open an issue of course :)

<details>
<summary>traceback</summary>
<pre>
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
web_1  |     self.dialect.do_execute(
web_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
web_1  |     cursor.execute(statement, parameters)
web_1  | psycopg2.errors.DuplicateTable: relation "idx_cities_geo" already exists
web_1  |
web_1  |
web_1  | The above exception was the direct cause of the following exception:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/bin/flask", line 8, in <module>
web_1  |     sys.exit(main())
web_1  |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 988, in main
web_1  |     cli.main()
web_1  |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 579, in main
web_1  |     return super().main(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
web_1  |     rv = self.invoke(ctx)
web_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
web_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
web_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
web_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
web_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
web_1  |     return ctx.invoke(self.callback, **ctx.params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
web_1  |     return __callback(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
web_1  |     return f(get_current_context(), *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 427, in decorator
web_1  |     return __ctx.invoke(f, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
web_1  |     return __callback(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/flask_migrate/cli.py", line 149, in upgrade
web_1  |     _upgrade(directory, revision, sql, tag, x_arg)
web_1  |   File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 98, in wrapped     
web_1  |     f(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 185, in upgrade    
web_1  |     command.upgrade(config, revision, sql=sql, tag=tag)
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 322, in upgrade
web_1  |     script.run_env()
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 569, in run_env
web_1  |     util.load_python_file(self.dir, "env.py")
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
web_1  |     module = load_module_py(module_id, path)
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
web_1  |     spec.loader.exec_module(module)  # type: ignore
web_1  |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "/usr/src/app/migrations/env.py", line 100, in <module>
web_1  |     run_migrations_online()
web_1  |   File "/usr/src/app/migrations/env.py", line 94, in run_migrations_online
web_1  |     context.run_migrations()
web_1  |   File "<string>", line 8, in run_migrations
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 853, in run_migrations
web_1  |     self.get_context().run_migrations(**kw)
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
web_1  |     step.migration_fn(**kw)
web_1  |   File "/usr/src/app/migrations/versions/c7707dc7c45a_.py", line 30, in upgrade
web_1  |     op.create_index('idx_cities_geo', 'cities', ['geo'], unique=False, postgresql_using='gist', postgresql_ops={})
web_1  |   File "<string>", line 8, in create_index
web_1  |   File "<string>", line 3, in create_index
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/operations/ops.py", line 966, in create_index
web_1  |     return operations.invoke(op)
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/operations/base.py", line 394, in invoke
web_1  |     return fn(self, operation)
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 99, in create_index
web_1  |     operations.impl.create_index(idx)
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/ddl/postgresql.py", line 84, in create_indexweb_1  |     self._exec(CreateIndex(index))
web_1  |   File "/usr/local/lib/python3.9/site-packages/alembic/ddl/impl.py", line 195, in _exec
web_1  |     return conn.execute(construct, multiparams)
web_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1306, in execute   
web_1  |     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
web_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
web_1  |     return connection._execute_ddl(
web_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1398, in _execute_ddl
web_1  |     ret = self._execute_context(
web_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
web_1  |     self._handle_dbapi_exception(
web_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
web_1  |     util.raise_(
web_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_     
web_1  |     raise exception
web_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
web_1  |     self.dialect.do_execute(
web_1  |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
web_1  |     cursor.execute(statement, parameters)
web_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "idx_cities_geo" already exists
web_1  |
web_1  | [SQL: CREATE INDEX idx_cities_geo ON cities USING gist (geo)]
web_1  | (Background on this error at: https://sqlalche.me/e/14/f405)
</pre>
</details>

I get this error when I run the migration with flask:
```
flask db migrate
flask db upgrade
```
(I have some costum alembic.ini and env.py so I don't initilize the migration in this project). Since flask, flask-migrate and a lot of library are involved I can't be sure it's GeoAlchemy2 but I noticed that I don't have this traceback with the previous versione of GeoAlchemy2 mentioned above (I could also provide a branch repository of my project with this error and it's quie easy to test, since it's in docker, but it will be filled with too much "stuff").
Let me know if it's better to open an issue and feel free to move/delete my comment.

**Comment by adrien-berchet** [comment]
Hi @Franc-Brs 
I changed a lot of things regarding the reflection mechanism of spatial tables in `GeoAlchemy2==0.12` and how it interacts with Alembic, so it's quite expected that a few things might break. In your case, I suspect that the migration script creates the table or the column without the flag `spatial_index=False`. So the column is created, an index is automatically created with it, and then Alembic tries to create it again, thus the error. If it's not that, I will need more information about your issue (at least the `alembic.ini` and `env.py` files).

**Comment by Franc-Brs** [comment]
> spatial_index=False

Ok, thank you. I'm not quite sure where I should put the declaration of the bool `spatial_index`. here you can find my [`env.py`](https://github.com/Franc-Brs/flask-ol-postgis/blob/main/services/web/migrations/env.py) and [`alembic.ini`](https://github.com/Franc-Brs/flask-ol-postgis/blob/main/services/web/migrations/alembic.ini): I added one line to alembic.ini and some functions to env.py in order to keep `spatial_ref_sys` table (I used [this](https://github.com/miguelgrinberg/Flask-Migrate/issues/18) issue as inspiration).  Btw, the models is something like this
```python
class City(db.Model):
    """A city, including its geospatial data. - thks https://www.jennifergd.com/post/7/"""

    __tablename__ = "cities"

    point_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    location = db.Column(db.String(30))
    longitude = db.Column(db.Float)
    latitude = db.Column(db.Float)
    geo = db.Column(Geometry(geometry_type="POINT"))
   ```

**Comment by adrien-berchet** [comment]
Ah sorry I should have been more explicit, the `spatial_index=False` should be in the migration script (from your traceback it should be in `/usr/src/app/migrations/versions/c7707dc7c45a_.py`).
Anyway, `GeoAlchemy2==0.12.1` provides [Alembic helpers](https://geoalchemy-2.readthedocs.io/en/latest/alembic_helpers.html) to be used in migration scripts and there are also hpers to [auto-generate migration scripts](https://geoalchemy-2.readthedocs.io/en/latest/alembic.html#helpers) so I suggest trying to use them. If you auto-generate the migration script with the helpers it should automatically take care of the `spatial_index=False`.

**Comment by Franc-Brs** [comment]
ok thank you for the link to docu and for the insight. I was able to run the stack without error and with the latest `GeoAlchemy2` release by adding the spatial index bool value (to `False`) in my `models.py`. I will dive in the links that you provided asap: I noticed that when I try to use the helpers as explaind (importing in the env.py)

<details>
<summary>traceback</summary>
<pre>
web    | Traceback (most recent call last):
web    |   File "/usr/local/bin/flask", line 8, in <module>
web    |     sys.exit(main())
web    |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 988, in main
web    |     cli.main()
web    |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 579, in main
web    |     return super().main(*args, **kwargs)
web    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
web    |     rv = self.invoke(ctx)
web    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
web    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
web    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
web    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
web    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
web    |     return ctx.invoke(self.callback, **ctx.params)
web    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
web    |     return __callback(*args, **kwargs)
web    |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
web    |     return f(get_current_context(), *args, **kwargs)
web    |   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 427, in decorator
web    |     return __ctx.invoke(f, *args, **kwargs)
web    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
web    |     return __callback(*args, **kwargs)
web    |   File "/usr/local/lib/python3.9/site-packages/flask_migrate/cli.py", line 149, in upgrade
web    |     _upgrade(directory, revision, sql, tag, x_arg)
web    |   File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 98, in wrapped
web    |     f(*args, **kwargs)
web    |   File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 185, in upgrade
web    |     command.upgrade(config, revision, sql=sql, tag=tag)
web    |   File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 322, in upgrade
web    |     script.run_env()
web    |   File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 569, in run_env
web    |     util.load_python_file(self.dir, "env.py")
web    |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
web    |     module = load_module_py(module_id, path)
web    |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
web    |     spec.loader.exec_module(module)  # type: ignore
web    |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
web    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web    |   File "/usr/src/app/migrations/env.py", line 10, in <module>
web    |     from geoalchemy2.alembic_helpers import render_item, include_object
web    | ImportError: cannot import name 'include_object' from 'geoalchemy2.alembic_helpers' (/usr/local/lib/python3.9/site-packages/geoalchemy2/alembic_helpers.py)     
</details>
</pre>

But I will give it a (better) try asap :)

**Comment by adrien-berchet** [comment]
Ok, that's a good first step then :-)
For your error, I realize that the doc is wrong... The `include_object` was removed and is not needed anymore. I created a PR to fix the doc: https://github.com/geoalchemy/geoalchemy2/pull/386. You can already check there the (hopefully) correct snippets for Alembic.

**Comment by karolzlot** [comment]
Is this issue solved and can be closed?

**Comment by adrien-berchet** [comment]
> Is this issue solved and can be closed?

As far as GeoAlchemy2 is concerned it should be fixed, though it would be nice if @Franc-Brs could confirm.

**Comment by jashwant** [comment]
Adding  `spatial_index=False` to `geoalchemy2.types.Geograph` method works for me.

**Comment by akvankorlaar** [comment]
Currently experiencing this issue with geoalchemy2 version 0.14.2.

The script crashes on .to_postgis with:
Error: psycopg2.errors.DuplicateTable: relation "idx_table_import_geometry" already exists

[SQL: CREATE INDEX idx_table_import_geometry ON bla.bla USING gist (geometry)]

My code:

```
        df.to_postgis(
            "bla",
            connection,
            schema="bla",
            if_exists="append",
        )
```

When checking my database, after running the script, this index does not exist.
All packages installed:

```
Successfully installed annotated-types-0.6.0 attrs-23.1.0 beautifulsoup4-4.12.2 boto3-1.28.7 boto3-type-annotations-0.3.1 botocore-1.31.7 certifi-2023.5.7 charset-normalizer-3.2.0 click-8.1.6 click-plugins-1.1.1 cligj-0.7.2 common-3.0.1 fiona-1.9.4.post1 geoalchemy2-0.14.2 geopandas-0.14.0 greenlet-2.0.2 idna-3.4 importlib-metadata-6.8.0 jmespath-1.0.1 numpy-1.25.1 opensearch-py-2.2.0 packaging-23.1 pandas-2.0.3 pillow-9.5.0 psycopg2-binary-2.9.6 pyairtable-1.5.0 pydantic-2.3.0 pydantic-core-2.6.3 pyproj-3.6.0 python-dateutil-2.8.2 pytz-2023.3 requests-2.31.0 s3transfer-0.6.1 segments-ai-1.2.0 shapely-2.0.1 simplejson-3.19.1 six-1.16.0 soupsieve-2.4.1 sqlalchemy-2.0.19 tqdm-4.66.1 types-pillow-10.0.0.3 types-requests-2.31.0.2 types-urllib3-1.26.25.14 typing-extensions-4.7.1 tzdata-2023.3 urllib3-1.26.16 zipp-3.16.2
```

Trace:

```
  File "/usr/local/lib/python3.9/site-packages/geopandas/geodataframe.py", line 2064, in to_postgis
    geopandas.io.sql._write_postgis(
  File "/usr/local/lib/python3.9/site-packages/geopandas/io/sql.py", line 461, in _write_postgis
    gdf.to_sql(
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/sql.py", line 1910, in to_sql
    table = self.prep_table(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/sql.py", line 1814, in prep_table
    table.create()
  File "/usr/local/lib/python3.9/site-packages/pandas/io/sql.py", line 914, in create
    self._execute_create()
  File "/usr/local/lib/python3.9/site-packages/pandas/io/sql.py", line 900, in _execute_create
    self.table.create(bind=self.pd_sql.con)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 1291, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2443, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 964, in visit_table
    self.traverse_single(index, create_ok=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 1001, in visit_index
    CreateIndex(index)._invoke_with(self.connection)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
    return bind.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1524, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
```

**Comment by adrien-berchet** [comment]
> Currently experiencing this issue with geoalchemy2 version 0.14.2.

Hi @akvankorlaar , I'm not able to reproduce your issue, could you provide a complete example please.
For the records, I tried the following script to create and insert a GeoDataFrame:
```python
from pathlib import Path

from shapely import wkt
import geopandas as gpd
import pandas as pd
import pytest

from sqlalchemy import create_engine
from sqlalchemy import Column, Integer
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import sessionmaker

from geoalchemy2 import Geometry


engine = create_engine("postgresql://gis:gis@localhost/gis", echo=True)
conn = engine.connect()
session = sessionmaker(bind=conn)()


class Base(DeclarativeBase):
    pass


class Point(Base):
    __tablename__ = "point"
    __table_args__ = {"schema": "gis"}
    id = Column(Integer, primary_key=True)
    geom = Column(Geometry(geometry_type="POINT", srid=4326))


@pytest.fixture
def setup_tables():
    Base.metadata.drop_all(conn, checkfirst=True)
    Base.metadata.create_all(conn, checkfirst=True)
    yield
    Base.metadata.drop_all(conn, checkfirst=True)


@pytest.fixture
def raw_data():
    return pd.DataFrame(
        [
            {"id": 1, "geom": "POINT(5 45)"},
            {"id": 999, "geom": "POINT(5.5 45.5)"},
        ]
    )


@pytest.fixture
def csv_points(raw_data, tmpdir):
    filepath = Path(tmpdir / "data.csv")
    if not filepath.exists():
        raw_data.to_csv(filepath, index=False)
    return filepath


@pytest.fixture
def db_points(setup_tables, raw_data):
    pts = []
    for elem in raw_data.to_dict("records"):
        # Create point
        p = Point()
        p.id = elem["id"]
        p.geom = f"SRID=4326;{elem['geom']}"
        pts.append(p.id)

        # Insert point
        session.add(p)
        session.flush()
        session.commit()
        session.expire(p)

    yield pts


def test_to_postgis(csv_points, db_points):
    df = pd.read_csv(csv_points)
    df["geom"] = df["geom"].apply(wkt.loads)
    df["id"] += 10
    crs = "EPSG:4326"
    gdf = gpd.GeoDataFrame(df, crs=crs, geometry="geom")
    gdf.to_postgis(
        "point",
        conn,
        schema="gis",
        if_exists="append",
    )

```
I ran it with Py3.11 and here is my `pip freeze`:
```
annotated-types==0.6.0 attrs==23.1.0 beautifulsoup4==4.12.2 boto3==1.28.7 boto3-type-annotations==0.3.1 botocore==1.31.7 certifi==2023.5.7 charset-normalizer==3.2.0 click==8.1.6 click-plugins==1.1.1 cligj==0.7.2 common==3.0.1 fiona==1.9.4.post1 geoalchemy2==0.14.2 geopandas==0.14.0 greenlet==2.0.2 idna==3.4 importlib-metadata==6.8.0 jmespath==1.0.1 numpy==1.25.1 opensearch-py==2.2.0 packaging==23.1 pandas==2.0.3 pillow==9.5.0 psycopg2-binary==2.9.6 pyairtable==1.5.0 pydantic==2.3.0 pydantic-core==2.6.3 pyproj==3.6.0 python-dateutil==2.8.2 pytz==2023.3 requests==2.31.0 s3transfer==0.6.1 segments-ai==1.2.0 shapely==2.0.1 simplejson==3.19.1 six==1.16.0 soupsieve==2.4.1 sqlalchemy==2.0.19 tqdm==4.66.1 types-pillow==10.0.0.3 types-requests==2.31.0.2 types-urllib3==1.26.25.14 typing-extensions==4.7.1 tzdata==2023.3 urllib3==1.26.16 zipp==3.16.2
```

**Comment by akvankorlaar** [comment]
Thanks for the resonse.
Ive tried to reproduce it myself today, but somehow it **did** work now :S.
What I do know for sure is that the error did occur, the version was 0.14.2 and the table did not exist yet. If it did exist, there should also be no error, because of the "append" flag. This leaves me to think that there was probably something weird going on on our side although I do not know what. Might just be a false alarm. Sorry about that!

My docker:
```
FROM public.ecr.aws/docker/library/python:3.9.17-bullseye

RUN apt update
RUN apt install -y git postgresql-client postgis

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install the package
COPY ./requirements.txt ./
RUN pip install -r requirements.txt
```

Code:
```

import zipfile
import geopandas as gpd
from sqlalchemy import create_engine
import requests

conn_string = "postgresql://etcetc"
LOCAL_DOWNLOAD_PATH = "/tmp/download.shp.zip"


def download_file_from_url(
    url: str,
    download_file_path: str,
) -> None:
    """
    Download a file
    """
    with requests.get(url, stream=True) as response:
        response.raise_for_status()
        with open(download_file_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)


print("Downloading file")

download_file_from_url(
    "https://cadastre.data.gouv.fr/data/etalab-cadastre/latest/shp/departements/01/cadastre-01-parcelles-shp.zip",
    LOCAL_DOWNLOAD_PATH,
)

print("Extracting file")

with zipfile.ZipFile(LOCAL_DOWNLOAD_PATH, "r") as zip_ref:
    zip_ref.extractall("/tmp/")

print("Reading file")

df = gpd.read_file("/tmp/parcelles.shp")

engine = create_engine(conn_string)
conn = engine.connect()

print("Importing file")

df.to_postgis(
    "import_test2",
    conn,
    schema="pokpok",
    if_exists="append",
)

conn.commit()
```

**Comment by adrien-berchet** [comment]
> Thanks for the resonse. Ive tried to reproduce it myself today, but somehow it **did** work now :S. What I do know for sure is that the error did occur, the version was 0.14.2 and the table did not exist yet. If it did exist, there should also be no error, because of the "append" flag. This leaves me to think that there was probably something weird going on on our side although I do not know what. Might just be a false alarm. Sorry about that!

Ok, no problem :-)
So for now let's consider it was a false alarm.
See you next time it happens again! :smile:

**Comment by k0ala** [comment]
I also observe this error with geopandas 0.14.2, sqlalchemy 2.0.38, importing into Postgres.
`ImportError: 'to_postgis()' requires geoalchemy2 package.`

**Comment by adrien-berchet** [comment]
> I also observe this error with geopandas 0.14.2, sqlalchemy 2.0.38, importing into Postgres. `ImportError: 'to_postgis()' requires geoalchemy2 package.`

Hi @k0ala 
As the error reports: you have to install GeoAlchemy2 to use `to_postgis()`. Could you check it is installed in your environment? If it is not, you have to install it with the command `pip install geoalchemy2`

**Comment by k0ala** [comment]
You're right, it wasn't installed.

**Comment by adrien-berchet** [comment]
Hehe ok :⁠-⁠)
